[package]
name = "day09"
version = "0.1.0"
authors = ["Ethan Mott <ethanmott@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
itertools = "0.9.0"
